[package]
name = "na"
version = "0.1.0"
authors = ["srdja <i@srdja.me>"]
build = "build.rs"

[dependencies]
libc = "*"
mime = "0.1.3"
hyper = "*"
getopts = "*"
regex = "*"

[build-dependencies]
gcc = "*"